image: ubuntu:20.04

stages:
  - compile
  - test
  - delivery

# Задаём команды, которые будут выполнены до прогона скриптов
before_script:
  - apt-get -y update
  - export DEBIAN_FRONTEND=noninteractive
  - export TZ=Europe/Moscow

# Собираем проект
build-code:
  stage: compile
  script:
  # Устанавливаем пакеты
  - apt-get -y install gcc g++ make cmake
  - g++ --version
  # Собираем
  - ./gomake
  # Сохраняем в артефактах
  artifacts:
    paths:
    - bin/*
    expire_in: 30 minutes

# Автотесты
test-all:
  stage: test
  script:
  - chmod +x test/make-result*
  - chmod +x test/test
  - chmod +x test/stress
  - test/test
  - test/stress

# Используем GitLab Pages для публикации Doxygen-документации
pages:
  stage: delivery
  script:
  # Устанавливаем пакеты
  - apt-get -y install gcc g++ make cmake doxygen graphviz lcov
  # Прогоняем Doxygen
  - doxygen doc/Doxyfile.cfg
  # Прогоняем сборку
  - ./gomakec
  # Прогоняем тесты
  - chmod +x test/make-result*
  - chmod +x test/test
  - test/test
  # Строим отчёт покрытия
  - lcov -t "lab" -o lab.info -c -d . --no-external
  - genhtml -o coverage lab.info
  # Диплоим
  - mv doc/html/ public/
  - mv coverage/ public/coverage/

  coverage: /^\s*lines\.*:\s+\d+\.\d+%/

  artifacts:
    paths:
    - public

  only:
  - main
